apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    labels:
        app: phone-app
    name: phone-app
spec:
    replicas: 1
    selector:
        matchLabels:
            app: phone-app
    template:
        metadata:
            labels:
                app: phone-app
                actorSystemName: showdown
        spec:
            containers:
            -   name: phone-app
                image: clusteringsolutionsshowdown/phone-app:13
                livenessProbe:
                    tcpSocket:
                        port: 8558
                ports:
                # akka remoting
                -   name: remoting
                    containerPort: 2552
                    protocol: TCP
                # akka-management bootstrap
                -   name: bootstrap
                    containerPort: 8558
                    protocol: TCP
                # external http
                -   name: akka-mgmt-http
                    containerPort: 8558
                    protocol: TCP
                env:
                -   name: NAMESPACE
                    valueFrom:
                        fieldRef:
                            fieldPath: metadata.namespace
                volumeMounts:
                -   name: config-volume
                    mountPath: /config
            volumes:
            -   name: config-volume
                configMap:
                    name: akka-config
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: pod-reader
rules:
-   apiGroups: [""] # "" indicates the core API group
    resources: ["pods"]
    verbs: ["get", "watch", "list"]
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
    name: read-pods
subjects:
# Note the `name` line below. The first default refers to the namespace. The second refers to the service account name.
# For instance, `name: system:serviceaccount:myns:default` would refer to the default service account in namespace `myns`
-   kind: ServiceAccount
    name: default
roleRef:
    kind: Role
    name: pod-reader
    apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ConfigMap
metadata:
    name: akka-config
data:
    akka.conf: |-
        include "application"

        akka {
          loglevel = "INFO"
        }